import { ConventionEvent, Day, FocusGroup, Category } from './types';

export const EVENTS: ConventionEvent[] = [
  // Thursday
  {
    id: 'th-01',
    title: 'Registration & Check-In',
    day: Day.Thursday,
    startTime: '11:00 AM',
    endTime: '11:00 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'Registration verification and room assignments'
  },
  {
    id: 'th-02',
    title: 'Refreshments',
    day: Day.Thursday,
    startTime: '11:00 AM',
    endTime: '3:15 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Social,
    description: 'Coffee and Snacks'
  },
  {
    id: 'th-03',
    title: 'Holy Qurbana (English)',
    day: Day.Thursday,
    startTime: '3:30 PM',
    endTime: '5:30 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Liturgy,
    description: 'Main celebrant: Major Archbishop Raphael Thattil'
  },
  {
    id: 'th-04',
    title: 'Dinner',
    day: Day.Thursday,
    startTime: '5:30 PM',
    endTime: '7:30 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Social,
    description: 'Buffet-style dinner'
  },
  {
    id: 'th-05',
    title: 'Opening Ceremony',
    day: Day.Thursday,
    startTime: '6:30 PM',
    endTime: '6:45 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Social,
    description: 'Opening performance by Cathedral Artists'
  },
  {
    id: 'th-06',
    title: 'Fusion Artists Staging',
    day: Day.Thursday,
    startTime: '6:45 PM',
    endTime: '7:00 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'Final alignment before fusion performance'
  },
  {
    id: 'th-07',
    title: 'Thaala Vismayam',
    day: Day.Thursday,
    startTime: '7:00 PM',
    endTime: '7:30 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'A grand fusion of 100+ Chenda artists and piano, led by Jayaram and Stephen Devassy'
  },
  {
    id: 'th-08',
    title: 'Jubilee Inauguration',
    day: Day.Thursday,
    startTime: '7:40 PM',
    endTime: '8:40 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Social,
    description: 'Inauguration of the Jubilee Convention and honoring the jubilee of Mar Jacob Angadiath'
  },
  {
    id: 'th-09',
    title: 'Cultural Program',
    day: Day.Thursday,
    startTime: '8:45 PM',
    endTime: '10:30 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Social,
    description: 'Showcase by Cathedral Cultural Academy'
  },
  // Friday
  {
    id: 'fr-01',
    title: 'Morning Meditation',
    day: Day.Friday,
    startTime: '6:00 AM',
    endTime: '6:30 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Liturgy,
    description: 'TBD'
  },
  {
    id: 'fr-02',
    title: 'Rosary & Adoration',
    day: Day.Friday,
    startTime: '6:30 AM',
    endTime: '7:30 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Liturgy,
    description: 'Led by Sehion team/Other teams/Sisters'
  },
  {
    id: 'fr-03',
    title: 'Confession',
    day: Day.Friday,
    startTime: '6:30 AM',
    endTime: '7:30 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Liturgy,
    description: 'Priests on duty'
  },
  {
    id: 'fr-04',
    title: 'Breakfast',
    day: Day.Friday,
    startTime: '6:30 AM',
    endTime: '8:00 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Social,
    description: 'Buffet breakfast'
  },
  {
    id: 'fr-05',
    title: 'Procession Staging',
    day: Day.Friday,
    startTime: '8:00 AM',
    endTime: '8:15 AM',
    venue: 'W375DE',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'Staging for procession'
  },
  {
    id: 'fr-06',
    title: 'Procession',
    day: Day.Friday,
    startTime: '8:15 AM',
    endTime: '9:15 AM',
    venue: 'Convention Center',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'Circular procession around the perimeter of the main convention hall.'
  },
  {
    id: 'fr-07',
    title: 'Holy Qurbana (English)',
    day: Day.Friday,
    startTime: '9:30 AM',
    endTime: '11:00 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Liturgy,
    description: 'Bishop Mar Tharayil (TBD)'
  },
  {
    id: 'fr-08',
    title: 'Introducing Bishop Fernandez',
    day: Day.Friday,
    startTime: '11:15 AM',
    endTime: '11:20 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Keynote,
    description: 'Bishop Joy introduces Bishop Fernandez'
  },
  {
    id: 'fr-09',
    title: 'Keynote Address – Evolving from a transplanted community to a fully native Church',
    day: Day.Friday,
    startTime: '11:20 AM',
    endTime: '11:50 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Keynote,
    description: 'Bishop Earl K. Fernandez'
  },
  {
    id: 'fr-10',
    title: 'Panel Discussion Anchored by Varughese Maliekkal',
    day: Day.Friday,
    startTime: '11:50 AM',
    endTime: '12:20 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Keynote,
    description: 'An engaging session on shaping the next 25 years of our diocese — goals, the way forward, and everyone’s role- Varughese Maliekkal'
  },
  {
    id: 'fr-11',
    title: 'Concluding Remarks',
    day: Day.Friday,
    startTime: '12:20 PM',
    endTime: '12:30 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Keynote,
    description: 'Major Archbishop Mar Raphael Thattil will formally conclude the discussion with his guidance and perspective'
  },
  {
    id: 'fr-12',
    title: 'Lunch',
    day: Day.Friday,
    startTime: '12:30 PM',
    endTime: '2:30 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Social,
    description: 'Buffet Lunch'
  },
  {
    id: 'fr-13',
    title: 'Trustees as Leaders- Practical steps to handle disagreements',
    day: Day.Friday,
    startTime: '1:30 PM',
    endTime: '2:30 PM',
    venue: 'Room 101',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'Mar Andrew Thazhathu'
  },
  {
    id: 'fr-14',
    title: 'Building Wealth - Basics of building wealth early',
    day: Day.Friday,
    startTime: '1:30 PM',
    endTime: '2:30 PM',
    venue: 'Room 201',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'TBD'
  },
  {
    id: 'fr-15',
    title: 'Supporting Young Adults in Their Marriage Journey',
    day: Day.Friday,
    startTime: '1:30 PM',
    endTime: '2:30 PM',
    venue: 'Room 301',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'Mar George Koovakattu'
  },
  {
    id: 'fr-16',
    title: 'Exploring Homeschooling',
    day: Day.Friday,
    startTime: '1:30 PM',
    endTime: '2:30 PM',
    venue: 'Room 401',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'TBD'
  },
  {
    id: 'fr-17',
    title: 'Supporting individuals navigating mental health challenges',
    day: Day.Friday,
    startTime: '3:00 PM',
    endTime: '4:00 PM',
    venue: 'Room 101',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'Clinical Psychologist and Local Experts'
  },
  {
    id: 'fr-18',
    title: 'Dating Do’s & Don’ts',
    day: Day.Friday,
    startTime: '3:00 PM',
    endTime: '4:00 PM',
    venue: 'Room 201',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'TBD'
  },
  {
    id: 'fr-19',
    title: 'Holy Qurbana - Signs and Symbols',
    day: Day.Friday,
    startTime: '3:00 PM',
    endTime: '4:00 PM',
    venue: 'Room 301',
    focusGroup: FocusGroup.All,
    category: Category.Liturgy,
    description: 'Dr. Manoj'
  },
  {
    id: 'fr-20',
    title: 'Envisioning Life After 60',
    day: Day.Friday,
    startTime: '3:00 PM',
    endTime: '4:00 PM',
    venue: 'Room 401',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'TBD'
  },
  {
    id: 'fr-21',
    title: 'Business Meet',
    day: Day.Friday,
    startTime: '4:15 PM',
    endTime: '5:15 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.YoungAdults,
    category: Category.Workshop,
    description: 'Business session by Josey'
  },
  {
    id: 'fr-22',
    title: 'Dinner',
    day: Day.Friday,
    startTime: '5:30 PM',
    endTime: '7:30 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Social,
    description: 'Buffet Dinner'
  },
  {
    id: 'fr-23',
    title: 'Dinner for Sponsors',
    day: Day.Friday,
    startTime: '6:00 PM',
    endTime: '7:30 PM',
    venue: 'TBD',
    focusGroup: FocusGroup.All,
    category: Category.Social,
    description: 'Plated Dinner'
  },
  {
    id: 'fr-24',
    title: 'Parish Fest',
    day: Day.Friday,
    startTime: '6:00 PM',
    endTime: '10:30 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Social,
    description: 'A 15 minute cultural, artistic, or spiritual showcase by each parish.'
  },
  // Saturday
  {
    id: 'sa-01',
    title: 'Morning Meditation',
    day: Day.Saturday,
    startTime: '6:00 AM',
    endTime: '6:30 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Liturgy,
    description: 'TBD'
  },
  {
    id: 'sa-02',
    title: 'Rosary & Adoration',
    day: Day.Saturday,
    startTime: '6:30 AM',
    endTime: '7:30 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Liturgy,
    description: 'Led by Sehion team/Other teams/Sisters'
  },
  {
    id: 'sa-03',
    title: 'Confession',
    day: Day.Saturday,
    startTime: '6:30 AM',
    endTime: '7:30 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Liturgy,
    description: 'Priests on duty'
  },
  {
    id: 'sa-04',
    title: 'Breakfast',
    day: Day.Saturday,
    startTime: '6:30 AM',
    endTime: '8:00 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Social,
    description: ''
  },
  {
    id: 'sa-05',
    title: 'Praise and Workship',
    day: Day.Saturday,
    startTime: '8:15 AM',
    endTime: '8:30 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'Stephen Devassy/Jesus Youth'
  },
  {
    id: 'sa-06',
    title: 'Holy Qurbana (Malayalam)',
    day: Day.Saturday,
    startTime: '8:30 AM',
    endTime: '10:00 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Liturgy,
    description: 'Main Celbrant- Mar Koovakattu, Homily- Mar Thazathu'
  },
  {
    id: 'sa-07',
    title: 'Opening Remarks by Anchor',
    day: Day.Saturday,
    startTime: '10:15 AM',
    endTime: '10:20 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Keynote,
    description: 'Introducing the keynote speaker'
  },
  {
    id: 'sa-08',
    title: 'Keynote Address – Parenting in a multi cultural environment',
    day: Day.Saturday,
    startTime: '10:20 AM',
    endTime: '10:50 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Keynote,
    description: 'TBD'
  },
  {
    id: 'sa-09',
    title: 'Panel Discussion',
    day: Day.Saturday,
    startTime: '10:50 AM',
    endTime: '11:20 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Keynote,
    description: 'Structure TBD'
  },
  {
    id: 'sa-10',
    title: 'Concluding Remarks',
    day: Day.Saturday,
    startTime: '11:20 AM',
    endTime: '11:30 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Keynote,
    description: 'by Anchor - TBD'
  },
  {
    id: 'sa-11',
    title: 'Immigrants to Influencers',
    day: Day.Saturday,
    startTime: '11:45 AM',
    endTime: '12:15 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Keynote,
    description: 'Vivek Ramaswamy or Usha Vance'
  },
  {
    id: 'sa-12',
    title: 'Immigrants to Influencers - QA Session',
    day: Day.Saturday,
    startTime: '12:15 PM',
    endTime: '12:30 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Keynote,
    description: 'Audience'
  },
  {
    id: 'sa-13',
    title: 'Lunch',
    day: Day.Saturday,
    startTime: '12:30 PM',
    endTime: '2:30 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Social,
    description: 'Buffet lunch'
  },
  {
    id: 'sa-14',
    title: 'Special Event for Trustees, Pioneers and SMCA',
    day: Day.Saturday,
    startTime: '1:30 PM',
    endTime: '2:30 PM',
    venue: 'Room 101',
    focusGroup: FocusGroup.Clergy,
    category: Category.Workshop,
    description: 'Lay Leadership and Vision - Dr. Jose Periapuram'
  },
  {
    id: 'sa-15',
    title: 'Aging with Grace',
    day: Day.Saturday,
    startTime: '1:30 PM',
    endTime: '2:30 PM',
    venue: 'Room 201',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'Fr. Bobby Jose Kattikad'
  },
  {
    id: 'sa-16',
    title: 'LGBTQ+ & Gender Issues',
    day: Day.Saturday,
    startTime: '1:30 PM',
    endTime: '2:30 PM',
    venue: 'Room 301',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'Panel with Mar Koovakkattu and Mar Thazhathu'
  },
  {
    id: 'sa-17',
    title: 'Special Event for Women',
    day: Day.Saturday,
    startTime: '3:00 PM',
    endTime: '4:00 PM',
    venue: 'Room 101',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'Women Helping Women Rise'
  },
  {
    id: 'sa-18',
    title: 'Spiritually Syro-Malabar, Socially Not',
    day: Day.Saturday,
    startTime: '3:00 PM',
    endTime: '4:00 PM',
    venue: 'Room 201',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'Mar Tharayil'
  },
  {
    id: 'sa-19',
    title: 'Dating Boundaries',
    day: Day.Saturday,
    startTime: '3:00 PM',
    endTime: '4:00 PM',
    venue: 'Room 301',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'Femya & Jesslyn'
  },
  {
    id: 'sa-20',
    title: 'Special Event for Sacristans, Choir and  Vincent D\' Paul',
    day: Day.Saturday,
    startTime: '4:30 PM',
    endTime: '5:30 PM',
    venue: 'Room 101',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'Behind the Mass/Living the Gospel Through Service and Solidarity'
  },
  {
    id: 'sa-21',
    title: 'Harmony in Marriage',
    day: Day.Saturday,
    startTime: '4:30 PM',
    endTime: '5:30 PM',
    venue: 'Room 201',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'Fr. Joseph Puthenpurackal'
  },
  {
    id: 'sa-22',
    title: 'Dual Identity Challenges',
    day: Day.Saturday,
    startTime: '4:30 PM',
    endTime: '5:30 PM',
    venue: 'Room 301',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'Fr. Bince'
  },
  {
    id: 'sa-23',
    title: 'Dinner',
    day: Day.Saturday,
    startTime: '5:30 PM',
    endTime: '7:30 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Social,
    description: 'Social gathering followed by Plated Dinner'
  },
  {
    id: 'sa-24',
    title: 'Closing Ceremony',
    day: Day.Saturday,
    startTime: '6:30 PM',
    endTime: '8:15 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Social,
    description: 'Formal concluding session'
  },
  {
    id: 'sa-25',
    title: 'Performance by Celebrity Artists',
    day: Day.Saturday,
    startTime: '8:30 PM',
    endTime: '10:30 PM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Social,
    description: 'Jayaram, Stephen Devassy, Nitya Mammen'
  },
  // Sunday
  {
    id: 'su-01',
    title: 'Breakfast',
    day: Day.Sunday,
    startTime: '6:30 AM',
    endTime: '8:00 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Social,
    description: 'Buffet breakfast'
  },
  {
    id: 'su-02',
    title: 'Traveler’s Qurbana',
    day: Day.Sunday,
    startTime: '7:00 AM',
    endTime: '8:00 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Liturgy,
    description: 'Holy Qurbana for early departures'
  },
  {
    id: 'su-03',
    title: 'Vote of Thanks',
    day: Day.Sunday,
    startTime: '8:15 AM',
    endTime: '8:45 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Workshop,
    description: 'Appreciation remarks'
  },
  {
    id: 'su-04',
    title: 'Holy Qurbana',
    day: Day.Sunday,
    startTime: '9:00 AM',
    endTime: '10:30 AM',
    venue: 'Convention Hall',
    focusGroup: FocusGroup.All,
    category: Category.Liturgy,
    description: 'Solemn closing Qurbana'
  }
];
